// each of these matches a command file in commands/utility
// messageCreate.js will check the message against these patterns and if it matches, it will execute the command
// the pattern is a regex that matches the command name and any arguments
module.exports.patterns = {
	"aboutgame": /^about|info|(game info)|version$/i,
	"arm": /^arm (?<object>.*)$/i,
	"attack": /^attack (?<target>.*)$/i,
	"close": /^close (?<object>.*)$/i,
	"drink": /^drink (?<object>.*)$/i,
	"drop": /^(drop|discard|(put down)|throw) (?<object>.*)$/i,
	"eat": /^eat (?<object>.*)$/i,
	"emote": /^emote (?<text>.*)$/i,
	"examine": /^(x|examine) (?<object>.*)$/i,
	"give": /^give (?<obj>.*) to (?<to>)$/i,
	"go": /^go (?<direction>(north|n|northwest|nw|west|w|southwest|sw|south|s|southeast|se|east|e|northeast|ne|in|out|o|up|u|down|d))$/i,
	"north": /^(north|n)$/i,
	"south": /^(south|s)$/i,
	"east": /^(east|e)$/i,
	"west": /^(west|w)$/i,
	"northeast": /^(northeast|ne)$/i,
	"northwest": /^(northwest|nw)$/i,
	"southeast": /^(southeast|se)$/i, 
	"southwest": /^(southwest|sw)$/i,
	"up": /^(up|u)$/i,
	"down": /^(down|d)$/i,
	"in": /^in$/i,
	"out": /^(out|o)$/i,
	"help": /^help|commands|cmds|command$/i,
	"hint": /^(hint|hints)$/i,
	"inventory": /^(inv|i|inventory)$/i,
	"look": /^look|l$/i,
	"note": /(^note (?<text>.*)$)|(^\W)/i,
	"oops": /^oops (?<object>.*)$/i,
	"players": /^players|who$/i,
	"put": /^put (?<object1>.*) (?<placement>.*) (?<object2>.*)$/i,
	"quitgame": /^(quit|exit|leave) game$/i,
	"read": /^read (?<object>.*)$/i,
	"reportbug": /^(report bug|bug) (?<description>)/i,
	"revive": /^revive (?<npc>.*)$/i,
	"saveprogress": /^save$/i,
	"siton": /^sit (on|in) (?<object>.*)$/i,
	"speakto": /^(speak|talk) to (?<npc>.*)$/i,
	"startgame": /^(start|begin) game$/i,
	"switchoff": /^(switch|turn) off (?<object>.*)$/i,
	"switchon": /^(switch|turn) on (?<object>.*)$/i,
	"take": /^(take|get) (?<object>.*)$/i,
	"test": /^test$/i,
	"undo": /^undo$/i,
	"use": /^use (?<object>.*)$/i,
	"useon": /^use (?<object1>.*) on (?<object2>.*)$/i,
	"wait": /^wait$/i,
	"watch": /^watch (?<object>.*)$/i,
	"weigh": /^weigh (?<object>.*)$/i,
	"xyzzy": /^xyzzzy$/i
};